### ISSUE TITLE
How to install correctly...?

### ISSUE THREAD

**Issue by OoLunar** [tinoschroeter/bash_on_steroids#3]
Here are the steps I've done to <i>attempt</i> to install BOS correctly.

- Update Apache2
- Added required lines to config
- Enabled cgid
- Restart Apache2, then:
```
project="subdomain2/admin/"
git clone https://github.com/tinoschroeter/bash_on_steroids.git /var/www/${project}
cd /var/www/${project}
sudo bash ./build.sh
```

- Navigated to my subdomain, index.htsh showing nothing but the text inside the document.

I <b>am using a subdomain</b> if that's any problem. I have also modified all file paths from ``/var/www/html`` to ``/var/www/subdomain2/`` if that's a problem.

Something that's best to add to this is to prompt the user of which filepath to add BOS too. This can be done by doing (bash code):
```
echo "Type which filepath BOS should use, followed by [ENTER]:"

read filepath

echo "Installing BOS to \"$filepath\""
```
Would lead to 
<b><i>Type which filepath BOS should use, followed by [ENTER]:
/var/www/subdomain2/
Installing BOS to "/var/www/subdomain2/"...
</b></i>

**Comment by tinoschroeter** [comment]
Hey, 
the only thing you need: is to put the build script in the same folder as your .htsh files.

_wget https://raw.githubusercontent.com/tinoschroeter/bash_on_steroids/master/build.sh_

This will take any .htsh file and build an "Bash CGI Script" out of it...you will find it in /usr/lib/cgi-bin/*.cgi

ScriptAlias "/index" "/usr/lib/cgi-bin/index.cgi" will map this to **http://yourdomain.tld/index**

**http://yourdomain.tld/cgi-bin/index.cgi** will also work ...

hope this will helps
