### ISSUE TITLE
DEMO Issue

### ISSUE THREAD

**Issue by gree303** [tinoschroeter/bash_on_steroids#4]
After installing running the vote DEMO from frontend results in a error.
In Detail some code is shown within the htsh within the browser.
`/dev/null;then voteing="yes" fi vote() { echo "$HTTP_X_FORWARDED_FOR" >> /tmp/voting } if [ "$vote" = "a" ] && [ "$voteing" = "no" ];then c=$(cat /tmp/a) a=$(( $c +1 )) echo $a > /tmp/a vote elif [ "$vote" = "b" ] && [ "$voteing" = "no" ];then c=$(cat /tmp/b) b=$(( $c +1 )) echo $b > /tmp/b vote fi ?>`
This happens when using a /html/subdir/,without subdirectory the index.htsh does work. 
Any tipp is very welcome, thanks.

**Comment by tinoschroeter** [comment]
The **index.htsh** file is only your **template** file ... the build script will generate an **cgi script** out of it 
and put it to the /usr/lib/cgi-bin folder 

Then you have to point your browser to `http://<your-ip>/cgi-bin/index.cgi `or use this:
`ScriptAlias "/index" "/usr/lib/cgi-bin/index.cgi"`

in your **apache config** && you have to enable **cgid** ` a2enmod cgid`

_This ist plain old cgi scripting_ 
 [Wikipedia Common_Gateway_Interface](https://en.wikipedia.org/wiki/Common_Gateway_Interface)
